INSERT INTO authors (first_name, last_name) VALUES  ('Joel', 'Richardson');
INSERT INTO authors (first_name, last_name) VALUES  ('Martin', 'King');
INSERT INTO authors (first_name, last_name) VALUES  ('Isla', 'Gray');
INSERT INTO authors (first_name, last_name) VALUES  ('Natalie', 'Rogers');
INSERT INTO authors (first_name, last_name) VALUES  ('Natasha', 'Owen');
INSERT INTO authors (first_name, last_name) VALUES  ('Nathan', 'Butler');
INSERT INTO authors (first_name, last_name) VALUES  ('Evelyn', 'Baker');
INSERT INTO authors (first_name, last_name) VALUES  ('Adam', 'Walker');
INSERT INTO authors (first_name, last_name) VALUES  ('Bradley', 'Clark');
INSERT INTO authors (first_name, last_name) VALUES  ('Danielle', 'Baker');
INSERT INTO authors (first_name, last_name) VALUES  ('James', 'Fox');
INSERT INTO authors (first_name, last_name) VALUES  ('Arthur', 'Lewis');
INSERT INTO authors (first_name, last_name) VALUES  ('Ellie', 'Cox');
INSERT INTO authors (first_name, last_name) VALUES  ('Amanda', 'Phillips');
INSERT INTO authors (first_name, last_name) VALUES  ('Dale', 'Robertson');
INSERT INTO authors (first_name, last_name) VALUES  ('Bethany', 'Brown');
INSERT INTO authors (first_name, last_name) VALUES  ('Wayne', 'Wilkinson');
INSERT INTO authors (first_name, last_name) VALUES  ('Ruby', 'Lloyd');
INSERT INTO authors (first_name, last_name) VALUES  ('Carlie', 'Morris');
INSERT INTO authors (first_name, last_name) VALUES  ('Maisie', 'Anderson');
INSERT INTO authors (first_name, last_name) VALUES  ('Amanda', 'Cox');

Insert Into books ( price, price_old, title, author_id) Values ( 776,991,'JCErX',8 );
Insert Into books ( price, price_old, title, author_id) Values ( 803,618,'KMHSfHdFvqTtzcFOCfDyQMUdfOMHmcSCSjmRVgVWu',5 );
Insert Into books ( price, price_old, title, author_id) Values ( 470,474,'QjrSQFEP VUEWA AlFQHLJqhqblZp',12 );
Insert Into books ( price, price_old, title, author_id) Values ( 378,458,'DiYKnVhouZEOinBcBSbpxEvDnLckeMPQDGjO',18 );
Insert Into books ( price, price_old, title, author_id) Values ( 571,551,'vsGiMClRhFxKGRQCkQbrOC',10 );
Insert Into books ( price, price_old, title, author_id) Values ( 820,355,'rwHPRkL woWZqrap',13 );
Insert Into books ( price, price_old, title, author_id) Values ( 72,801,'TSoFrCSbYL',16 );
Insert Into books ( price, price_old, title, author_id) Values ( 631,486,'pjLGWaUPzlKnqYXFMDCzHBoAgGIljAp',7 );
Insert Into books ( price, price_old, title, author_id) Values ( 832,95,'yUmCqGd',6 );
Insert Into books ( price, price_old, title, author_id) Values ( 376,71,'ueaWOmZhdOWB dRUpi TnwSH davYhSyzhJXBEKycbuB',8 );
Insert Into books ( price, price_old, title, author_id) Values ( 649,287,'yWqMXRIxzedUCqklPPrBoGVjwfZEbXUY',15 );
Insert Into books ( price, price_old, title, author_id) Values ( 986,393,'LG',16 );
Insert Into books ( price, price_old, title, author_id) Values ( 517,6,'Jb gojGktp oiWwJvSWGzFNqRsMCmkuclJeqUhDQpIyGsSdO',1 );
Insert Into books ( price, price_old, title, author_id) Values ( 13,102,'BPBAG',13 );
Insert Into books ( price, price_old, title, author_id) Values ( 34,51,'eyAoCkveiAUjFBmHhyTgUqALuu',10 );
Insert Into books ( price, price_old, title, author_id) Values ( 80,590,'TAdzTAKnnOqANvSMgnXYJiAuTVtZ',20 );
Insert Into books ( price, price_old, title, author_id) Values ( 441,945,'OPDRz',6 );
Insert Into books ( price, price_old, title, author_id) Values ( 829,676,'YOuNECzJanVMRcRdx',19 );
Insert Into books ( price, price_old, title, author_id) Values ( 727,237,'tgHvvroJrvdFnQCtsBgJvgEnh lvjkezCyL jIblghCjCjsli',17 );
Insert Into books ( price, price_old, title, author_id) Values ( 781,819,'wPJDBxm',10 );
Insert Into books ( price, price_old, title, author_id) Values ( 461,561,'YmSUFWsCQtouYtsgDjMBNVE',8 );
Insert Into books ( price, price_old, title, author_id) Values ( 755,524,'MMyPnQZJs',14 );
Insert Into books ( price, price_old, title, author_id) Values ( 335,600,'zBWmatNOgjLKNm',16 );
Insert Into books ( price, price_old, title, author_id) Values ( 465,596,'l BuRgmBxKvbiJJGlOOEqtOwCXSBjWEVf XOztMD',2 );
Insert Into books ( price, price_old, title, author_id) Values ( 492,125,'vwpVpHCDaamWqzMmrjlPprzqkcR',18 );
Insert Into books ( price, price_old, title, author_id) Values ( 842,57,'bvqQyyrfQIAqbEH JIqLra PySXdciOvzFT',11 );
Insert Into books ( price, price_old, title, author_id) Values ( 203,531,'ArsHRfehiwtBoqqvie',19 );
Insert Into books ( price, price_old, title, author_id) Values ( 51,380,'FNgW gWhyNbUcKzEXBxtpgqRG',12 );
Insert Into books ( price, price_old, title, author_id) Values ( 525,857,'zxCpGbTveD cMCqkIHRlTbNOVlDczMFGAPVwTNB ZD ',11 );
Insert Into books ( price, price_old, title, author_id) Values ( 589,572,'PCJedWGqPdLTBwtJaNiIIeceeMHybBRlQmtk',6 );
Insert Into books ( price, price_old, title, author_id) Values ( 407,251,'oyyIRPDObwGkzGkfLXzckxpILhVB',5 );
Insert Into books ( price, price_old, title, author_id) Values ( 428,743,'YfWlbXpeZEmkPwuvBOmjWQ',21 );
Insert Into books ( price, price_old, title, author_id) Values ( 365,142,'PurTAmQSIdUmLOqD',21 );
Insert Into books ( price, price_old, title, author_id) Values ( 506,848,'oIXisvHSbRNtNzRYDpzjVoy',13 );
Insert Into books ( price, price_old, title, author_id) Values ( 485,861,'Lh pBpnXfrnArwCHIZ GDkW',15 );
Insert Into books ( price, price_old, title, author_id) Values ( 443,218,'lwHFLWwtsGJKic',7 );
Insert Into books ( price, price_old, title, author_id) Values ( 403,331,'nW',18 );
Insert Into books ( price, price_old, title, author_id) Values ( 636,89,'wUsLyjcGuVbNexQYCSEZtQHxmABeyywKUyPhF',2 );
Insert Into books ( price, price_old, title, author_id) Values ( 173,547,'iASVFRnwHSwQENcnPWyhTo',2 );
Insert Into books ( price, price_old, title, author_id) Values ( 979,537,'nluLOdWWsSKGH nw',3 );
Insert Into books ( price, price_old, title, author_id) Values ( 194,960,'azuCWGgLUnvBEMHDqEgBfkuciRydmtNAUAXJzllJz',4 );
Insert Into books ( price, price_old, title, author_id) Values ( 115,872,'EbSyQqfMGKFFaMNOShUZDhUqjxyJKsDwPdNsfHcLLHD',12 );
Insert Into books ( price, price_old, title, author_id) Values ( 535,618,'DD GbZGDhrtSxlUDdwPcQM',2 );
Insert Into books ( price, price_old, title, author_id) Values ( 818,380,'Xu',3 );
Insert Into books ( price, price_old, title, author_id) Values ( 806,758,' wOhJQEwY aCmIKwm',13 );
Insert Into books ( price, price_old, title, author_id) Values ( 570,292,'ysmdJdRfQiGMHCEuuBZp JoXJJz',12 );
Insert Into books ( price, price_old, title, author_id) Values ( 738,947,'uetDfmsXHadxMzNj',12 );
Insert Into books ( price, price_old, title, author_id) Values ( 950,393,'NWDkgUyDKHQSaENSG',15 );
Insert Into books ( price, price_old, title, author_id) Values ( 172,41,'XvXRFDbkejKTeOL jqOiqDDqFQDKIskzIPdrjuNnTKnJJtBEdg',5 );
Insert Into books ( price, price_old, title, author_id) Values ( 492,231,'mYvUIVTqaSmhmSqfiwKUwpIMKWrMMNGChKkFLIDr ',2 );
Insert Into books ( price, price_old, title, author_id) Values ( 309,970,'lwNQAyqwogJqZ',19 );
Insert Into books ( price, price_old, title, author_id) Values ( 150,12,'yhIvaXPUGQaIyFZQeLZTsEnJvBwe',20 );
Insert Into books ( price, price_old, title, author_id) Values ( 554,655,'yUExbxmOomjtwQUVmcXdNYoFWLvDLeIgQMtxNanrTWpuTEsx',10 );
Insert Into books ( price, price_old, title, author_id) Values ( 836,950,'UlGdsVaMGmANXDXmsGZXC',10 );
Insert Into books ( price, price_old, title, author_id) Values ( 237,101,'KNGM sQGWlXiaoymHxRDgG',15 );
Insert Into books ( price, price_old, title, author_id) Values ( 738,54,'VNBPbuzlG',8 );
Insert Into books ( price, price_old, title, author_id) Values ( 849,120,'eXNvHO',7 );
Insert Into books ( price, price_old, title, author_id) Values ( 954,572,'qKlKFtjJOlUyWJIxIDLqCmutcuSQTOtnMyFNCeTAT',7 );
Insert Into books ( price, price_old, title, author_id) Values ( 326,431,'QVoYYPuGemAMtyFMlI Tvf wEQASqDuIHPbYSFpfjneem',7 );
Insert Into books ( price, price_old, title, author_id) Values ( 93,403,'QlyUTtSfp',21 );
Insert Into books ( price, price_old, title, author_id) Values ( 222,45,'uZJieiAJyPydYSTsovDUYezwUXx',20 );
Insert Into books ( price, price_old, title, author_id) Values ( 180,166,'UbCZvJAqimdWyzRWJwzzTeLGgauKCwSjhYlCOXxFSs',2 );
Insert Into books ( price, price_old, title, author_id) Values ( 325,519,'ztFWqOuGQuQyUeCood xDysRpHwtsfsZfvkveTWTsKdXWbO',20 );
Insert Into books ( price, price_old, title, author_id) Values ( 794,702,'gzVAniWLBEEqq',2 );
Insert Into books ( price, price_old, title, author_id) Values ( 852,283,'HaLcuQhIeYuiTJPhEqYoyzYfLgdbqWjRm',4 );
Insert Into books ( price, price_old, title, author_id) Values ( 145,892,'tHNvJiGcQM cwjFMsiFLEJbPCMAn cznpvUlgYeCSrCqvU',8 );
Insert Into books ( price, price_old, title, author_id) Values ( 320,58,'Ul vamQTUZFUgNl',9 );
Insert Into books ( price, price_old, title, author_id) Values ( 501,119,'Yqq NbtxTxNkesCvGdPDjPMBZQZw',9 );
Insert Into books ( price, price_old, title, author_id) Values ( 755,92,'aZOvJHMQnoDPjTztomdbfaPQBVWYTPDNtmrJmqivJHDyKo',14 );
Insert Into books ( price, price_old, title, author_id) Values ( 130,420,'onxFiMXKCLQs FceIB JxMWJkkfuQITVCAdBruZCFqStT',21 );
Insert Into books ( price, price_old, title, author_id) Values ( 706,586,'NQaiuLvHXFD',14 );
Insert Into books ( price, price_old, title, author_id) Values ( 569,593,'qKOSJaz',10 );
Insert Into books ( price, price_old, title, author_id) Values ( 505,355,'gEIbVlWuHUqhcFnd ESUXqnFLjfPXBIskw',14 );
Insert Into books ( price, price_old, title, author_id) Values ( 149,718,'wcwtJvidyUsIaiEWUjOAbkLDYNNcLRxcio YaQYzlse',16 );
Insert Into books ( price, price_old, title, author_id) Values ( 484,746,'KxwmqZdDgZfGvPIgATmznyfOrKBqKJ',10 );
Insert Into books ( price, price_old, title, author_id) Values ( 408,449,'tYroiR',11 );
Insert Into books ( price, price_old, title, author_id) Values ( 992,473,'PnleUcXbchIZvMJLmFafEmpzwK',6 );
Insert Into books ( price, price_old, title, author_id) Values ( 891,114,'EcvmAfxOzlURcWKnLUxfBiWYbes',18 );
Insert Into books ( price, price_old, title, author_id) Values ( 232,253,'pOjXWbHxbBVuiyvuanYLJefDmJPmbKyx LLXtLDhzxUGFeHzIm',16 );
Insert Into books ( price, price_old, title, author_id) Values ( 164,521,'sTitlVXN',15 );
Insert Into books ( price, price_old, title, author_id) Values ( 508,198,'gDzvcKoCHhkDNJxfrZtI',5 );
Insert Into books ( price, price_old, title, author_id) Values ( 248,863,'atNRlTiOgClMzphRbIP mHatC',21 );
Insert Into books ( price, price_old, title, author_id) Values ( 975,662,'SSZnlLmYv',1 );
Insert Into books ( price, price_old, title, author_id) Values ( 73,828,' jFunIJ',15 );
Insert Into books ( price, price_old, title, author_id) Values ( 64,722,'JDtoNZnyz',1 );
Insert Into books ( price, price_old, title, author_id) Values ( 644,900,'fGNAAQEtneBSuFcIPmDNmmoksKtNiRMupkhAJDvH',5 );
Insert Into books ( price, price_old, title, author_id) Values ( 9,630,'rRiqJziTVcHCeCqfyRJnzFtSJWnPezl wtNDCTRxX',11 );
Insert Into books ( price, price_old, title, author_id) Values ( 983,936,'hMhAua',2 );
Insert Into books ( price, price_old, title, author_id) Values ( 243,454,'R tLcUZjdrK YbRUzvW',17 );
Insert Into books ( price, price_old, title, author_id) Values ( 287,918,'TZZRekgssaKAmGhvV PozOWacMKNFwMh',3 );
Insert Into books ( price, price_old, title, author_id) Values ( 763,865,'sxsLmgIlXP',8 );
Insert Into books ( price, price_old, title, author_id) Values ( 904,836,'NzbFJTNxMqbJywdmoubOCjmgm gdLOrpGObaYVOA',9 );
Insert Into books ( price, price_old, title, author_id) Values ( 8,151,'okuFBZCufAiZkFhslxAEzQAgFBHdgjgIwP',2 );
Insert Into books ( price, price_old, title, author_id) Values ( 128,977,'wm',3 );
Insert Into books ( price, price_old, title, author_id) Values ( 18,10,'MqtdorLYQyjwCy',19 );
Insert Into books ( price, price_old, title, author_id) Values ( 816,767,'DkYZ YFTLKEZjo',17 );
Insert Into books ( price, price_old, title, author_id) Values ( 454,738,'vufStfdzldanfNVBppxv',2 );
Insert Into books ( price, price_old, title, author_id) Values ( 261,270,'MHHtoqIvepQ',7 );
Insert Into books ( price, price_old, title, author_id) Values ( 491,815,'cdxEhtBUnfSHNwYCaUyXfXuMdVSC',6 );
Insert Into books ( price, price_old, title, author_id) Values ( 364,333,'qvgml TuPUqeAaMjFhSHSAXHBwJTZmOnkpWInY',3 );

